lr: 0.001
x_dim: 5
y_dim: 2
sigma_eps: 0.001

data_horizon: 20
test_horizon: 10
meta_batch_size: 10

nn_layers: [128,128, 16]
activation: 'tanh'

# rocker-bogie params:
x_range: [0.0, 10.0]
v_range: [0.0, 1.0]
tau_range: [-2.0, 2.0]
mu_range: [0.90, 0.90]
# mu_range: [0.30, 0.90]
crr_range: [0.01, 0.01] # loose sand is 0.2
# crr_range: [0.0, 0.08] # loose sand is 0.2
dt: 0.1